package:
  name: iva-mt
  version: 0.2.0

source:
  url: https://github.com/cartesinus/iva_mt/archive/refs/tags/0.2.0.zip
  sha256: b210c82ce8a0bcb7f2fbf654ad1f8cf02d03019de989d3e671945c3d87f49844

channels:
  - pytorch
  - conda-forge
  - defaults

requirements:
  host:
    - python ==3.10
    - pip
  run:
    - python ==3.10
    - pytorch
    - transformers
    - sentencepiece
    - datasets
    - huggingface_accelerate
    - pip

test:
  imports:
    - iva_mt

about:
  home: https://github.com/cartesinus/iva_mt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A machine translation library utilizing m2m100 models, equipped with features for generating diverse verb variants via VerbNet and Conditional Beam Search to enrich Virtual Assistant training sets.'
  description: 'A machine translation library utilizing m2m100 models, equipped with features for generating diverse verb variants via VerbNet and Conditional Beam Search to enrich Virtual Assistant training sets.'
  doc_url: https://github.com/cartesinus/iva_mt
  dev_url: https://github.com/cartesinus/iva_mt

extra:
  recipe-maintainers:
    - cartesinus

